import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { centsToDollars } from "../api";
export function ResultCard({ result, loading, error }) {
    if (loading) {
        return (_jsxs("div", { className: "overflow-hidden rounded-xl border border-slate-200 bg-white shadow-card", children: [_jsxs("div", { className: "grid grid-cols-1 gap-px bg-slate-100 sm:grid-cols-2", children: [_jsx(SkeletonBlock, {}), _jsx(SkeletonBlock, {})] }), _jsx("div", { className: "border-t border-slate-100 px-6 py-3", children: _jsx("div", { className: "skeleton h-3 w-64" }) })] }));
    }
    if (error) {
        return (_jsx("div", { className: "rounded-xl border border-red-200 bg-red-50 p-6 text-sm text-red-700", children: error }));
    }
    if (!result) {
        return (_jsx("div", { className: "rounded-xl border border-dashed border-slate-300 bg-white p-6 text-sm text-slate-500", children: "Adjust the inputs on the left and your prediction will appear here." }));
    }
    const { prediction, annual_plan_share_median, annual_plan_share_mean } = result;
    return (_jsxs("div", { className: "overflow-hidden rounded-xl border border-slate-200 bg-white shadow-card", children: [_jsxs("div", { className: "grid grid-cols-1 gap-px bg-slate-100 sm:grid-cols-2", children: [_jsx(PredictionBlock, { title: "Typical year", tooltip: "50th percentile (median). Half of people like you spend less, half spend more. This is what you should expect in a normal year.", charges_cents: prediction.median_charges_cents, share: annual_plan_share_median }), _jsx(PredictionBlock, { title: "Long-run average", tooltip: "Mean (expected value). Includes the rare-but-expensive years that pull the average up. Better number for budgeting across many years.", charges_cents: prediction.mean_charges_cents, share: annual_plan_share_mean })] }), _jsxs("div", { className: "border-t border-slate-100 bg-slate-50 px-6 py-3 text-xs text-slate-500", children: ["80% interval for charges:", " ", _jsx("span", { className: "tabular-nums font-medium text-slate-700", children: centsToDollars(prediction.lower_bound_cents) }), " ", "to", " ", _jsx("span", { className: "tabular-nums font-medium text-slate-700", children: centsToDollars(prediction.upper_bound_cents) }), " ", "(10th to 90th percentile). Healthcare costs are heavily right-skewed; the interval is wide because real costs really are."] })] }));
}
function SkeletonBlock() {
    return (_jsxs("div", { className: "space-y-3 bg-white p-6", children: [_jsx("div", { className: "skeleton h-3 w-24" }), _jsx("div", { className: "skeleton h-8 w-32" }), _jsx("div", { className: "skeleton h-3 w-40" }), _jsxs("div", { className: "mt-4 space-y-2 border-t border-slate-100 pt-3", children: [_jsx("div", { className: "skeleton h-3 w-20" }), _jsx("div", { className: "skeleton h-7 w-28" }), _jsxs("div", { className: "mt-2 grid grid-cols-2 gap-y-1.5", children: [_jsx("div", { className: "skeleton h-3 w-20" }), _jsx("div", { className: "skeleton ml-auto h-3 w-16" }), _jsx("div", { className: "skeleton h-3 w-20" }), _jsx("div", { className: "skeleton ml-auto h-3 w-16" })] })] })] }));
}
function PredictionBlock({ title, tooltip, charges_cents, share, }) {
    return (_jsxs("div", { className: "bg-white p-6", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("div", { className: "text-xs font-semibold uppercase tracking-wider text-slate-400", children: title }), _jsx("abbr", { title: tooltip, className: "flex h-4 w-4 cursor-help items-center justify-center rounded-full bg-slate-100 text-[10px] font-bold text-slate-500 no-underline", children: "?" })] }), _jsx("div", { className: "mt-1 text-3xl font-bold tracking-tight text-slate-900 tabular-nums", children: centsToDollars(charges_cents) }), _jsx("div", { className: "mt-0.5 text-xs text-slate-400", children: "predicted annual charges" }), share && (_jsxs("div", { className: "mt-4 border-t border-slate-100 pt-3", children: [_jsx("div", { className: "text-xs font-semibold uppercase tracking-wider text-slate-400", children: "You would pay" }), _jsx("div", { className: "mt-0.5 text-2xl font-bold tracking-tight text-brand-600 tabular-nums", children: centsToDollars(share.member_pays_cents) }), _jsxs("dl", { className: "mt-3 space-y-1.5 text-xs", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("dt", { className: "text-slate-500", children: "Deductible" }), _jsx("dd", { className: "tabular-nums font-medium text-slate-700", children: centsToDollars(share.deductible_applied_cents) })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("dt", { className: "text-slate-500", children: "Coinsurance" }), _jsx("dd", { className: "tabular-nums font-medium text-slate-700", children: centsToDollars(share.coinsurance_cents) })] }), _jsxs("div", { className: "flex items-center justify-between border-t border-slate-100 pt-1.5", children: [_jsx("dt", { className: "text-slate-500", children: "Plan pays" }), _jsx("dd", { className: "tabular-nums font-medium text-emerald-600", children: centsToDollars(share.plan_pays_cents) })] })] }), share.capped_at_oop_max && (_jsx("div", { className: "mt-2.5 rounded-lg bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-700", children: "OOP max reached \u2014 plan absorbs the rest." }))] }))] }));
}
